config/routes.rb
Rails.application.routes.draw do
  root 'currencies#index'
  resources :currencies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def index
    title = "Currency Title"
    @currencies = Currency.all 
  end

  def new
    @currency = Currency.new
  end

  def show 
    @currency = Currency.find(params[:id])
  end

  def create
    @currency = Currency.new(currency_params)
    if @currency.save
      redirect_to root_path
    else
      render 'currency/new' 
    end
  end


  def currency_params
    params.require(:currency).permit(:money)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/index.html.erb
<h1>This is the index page</h1>

<h1><%= @title %></h1>

<% @currencies.each do |x| %>
<%= link_to x.money, currency_path(x) %>
<% end %>


<%= link_to "another page", new_currency_path %> 

app/views/currencies/new.html.erb
<h1>This is the new currency page</h1>

<%= form_for @currency do |f| %>
  Money: <%= f.text_field :money %><br/>
  <%= f.submit %>
  <% end %>

app/views/currencies/show.html.erb
<%= @currency.money %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fxcx</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>